#!/bin/sh

sudo apt-get install -y libgstreamer-plugins-base1.0-dev\
    libgstreamer-plugins-good1.0-dev\
    libgstreamer-plugins-bad1.0-dev\
    libgstrtspserver-1.0-dev

mkdir -p ~/rtsp_ws/src
cd ~/rtsp_ws
catkin_make
source ~/rtsp_ws/devel/setup.sh
cd ~/rtsp_ws/src
git clone https://github.com/parvusvox/ros_rtsp
cd ~/rtsp_ws

catkin_make pkg:=ros_rtsp

cd ~/rtsp_ws/src/ros_rtsp
USERNAME=$(whoami)
ROSVER=$(rosversion -d)
sed -i "s/ROSVER/${ROSVER}/g" roscore_temp.service
sed "s/USERNAME/${USERNAME}/g" roscore_temp.service > roscore.service
sed "s/USERNAME/${USERNAME}/g" roslaunch_temp.service > roslaunch.service

sudo cp roscore.service /etc/systemd/system
sudo cp roslaunch.service /etc/systemd/system
sudo cp roslaunch /usr/sbin

sudo systemctl enable roscore.service
sudo systemctl enable roslaunch.service
sudo chmod +x /usr/sbin/roslaunch
